# Generated by Django 4.0.10 on 2024-01-20 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=200, unique=True)),
                ('rate_star', models.FloatField(default=0)),
                ('genre', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('run_timing', models.IntegerField()),
                ('release_date', models.DateField()),
                ('image', models.URLField(max_length=500)),
                ('location', models.CharField(default='india', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=6)),
                ('is_reserver', models.BooleanField(default=False)),
                ('row', models.CharField(max_length=10)),
                ('seat_type', models.CharField(max_length=50)),
                ('seat_price', models.FloatField(default=0.0)),
                ('available_seats_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_num', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=0)),
                ('seats', models.ManyToManyField(to='Ticketapp.seats')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticketapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('movie_time', models.DateTimeField()),
                ('available_seats', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticketapp.movie')),
            ],
        ),
        migrations.AddField(
            model_name='seats',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticketapp.theater'),
        ),
    ]
